# Simultaneous linear equations

Today's notebook is short and sweet! Practice that array indexing!

In [1]:
import numpy as np

## Gaussian elimination

Let's say we want to solve a system of equations of the form 

$$\mathbf{A} \mathbf{x} = \mathbf{v}$$

where $\mathbf{A}$ is a matrix and $\mathbf{x}$ and $\mathbf{v}$ are both vectors. Clearly one way to solve this equation is to invert the matrix $\mathbf{A}$. That can be tricky, however. In this notebook we will explore a fast, accurate, and straightforward method for solving problems like this that does not involve a matrix inversion. The method is **Gaussian elimination**. To see how it works, recall that we can always do the following:

1. Multiply any of our simultaneous equations by a nonzero constant, and it's still the same equation.
2. Take any linear combination of two equations, and we get another correct equation.

Consider the following:

$$\left(\begin{matrix}
       2 & 1 & 4 \\
       3 & 4   & -1\\
       1 & -4  & 1 \\
\end{matrix}\right) \left(\begin{matrix} x_1 \\
x_2 \\
x_3\\
\end{matrix}\right) = \left(\begin{matrix} -4 \\
3 \\
9\\
\end{matrix}\right)$$

We are going to perform the operations 1 and 2 until we have re-expressed this system of equations as an **upper triangular** matrix, where all diagonal elements are 1 and only the upper righthand triangle of values is nonzero. 

To start with, let's divide the first row by 2 to make the upper lefthand element 1.

$$\left(\begin{matrix}
       1 & 0.5 & 2 \\
       3 & 4   & -1\\
       1 & -4  & 1 \\
\end{matrix}\right) \left(\begin{matrix} x_1 \\
x_2 \\
x_3\\
\end{matrix}\right) = \left(\begin{matrix} -2 \\
3 \\
9\\
\end{matrix}\right)$$

Notice that of course we have to divide both $\mathbf{A}$ and $\mathbf{v}$ by this value in the correct row. Now we turn our attention to the second row, which has a 3 as its first element. Let's eliminate that by subtracting 3 times the first row from the second, to get:

$$\left(\begin{matrix}
       1 & 0.5 & 2 \\
       0 & 2.5   & -7\\
       1 & -4  & 1 \\
\end{matrix}\right) \left(\begin{matrix} x_1 \\
x_2 \\
x_3\\
\end{matrix}\right) = \left(\begin{matrix} -2 \\
9 \\
9\\
\end{matrix}\right)$$

Keep it up until the first row of the matrix is $(1, 0, 0, 0)$, and then move on to the second row, and so on and so forth until we arrive at our upper triangular matrix:

$$\left(\begin{matrix}
       1 & 0.5 & 2 \\
       0 & 1   & -2.8\\
       0 & 0  & 1 \\
\end{matrix}\right) \left(\begin{matrix} x_1 \\
x_2 \\
x_3\\
\end{matrix}\right) = \left(\begin{matrix} -2 \\
3.6 \\
-2\\
\end{matrix}\right)$$

Now we can very simply read off the solutions to our equations using **backsubstitution**: clearly

$$x_3 = -2$$

which we just plug in to find $$x_2 = 3.6 - -2.8*x_3 = 3.6 - 5.6 = -2$$

and so on. Done! Let's tackle a concrete problem that requires us to code up Gaussian elimination. 

## Circuit of resistors

Consider the following circuit of resistors:



<img src="data/resistor_circuit.jpeg" alt="A circuit of nine resistors" width="300"/>


All the resistors have the same resistance $R$. $V_+$ at the top is at voltage $V_+$ = 5 V. What are the other four voltages, $V_1$ to $V_2$?

To answer this question we use Ohm's law and the Kirchhoff current law, which says that the total net current out of (or into) any junction in a circuit must be zero. For the junction at voltage $V_1$, for example, we find:

$$\frac{V_1 - V_2}{R} + \frac{V_1 - V_3}{R} + \frac{V_1 - V_4}{R} + \frac{V_1 - V_+}{R} = 0$$

which we can simplify to 

$$4 V_1 - V_2 - V_3 - V_4 = V_+$$

&#128310; Write similar equations for the other three junctions with unknown voltages. ✅

✍🏽 For the junction at $V_2$: 

$$\frac{V_2 - V_1}{R} + \frac{V_2 - 0}{R} + \frac{V_2 - V_4}{R} = 0$$
$$ 3 V_2 - V_1 - V_4 = 0 $$

For the junction at $V_3$: 

$$\frac{V_3 - V_4}{R} + \frac{V_3 - V_1}{R} + \frac{V_3 - V_+}{R} = 0$$
$$ 3 V_3 - V_4 - V_1 = V_+ $$

For the junction at $V_4$: 

$$\frac{V_4 - 0}{R} + \frac{V_4 - V_2}{R} + \frac{V_4 - V_1}{R} + \frac{V_4 - V_3}{R} = 0$$
$$ 4 V_4 - V_2 - V_1 - V_3 = 0 $$

&#128309; Define and print $\textbf{A}$ and $\textbf{v}$ as numpy arrays, following the comments below. ✅

In [80]:
# Define a numpy array A of type float filled with your values. Make this readable! Remember that you can have line breaks for expressions in parentheses.
A = np.array([[4, -1, -1, -1],
              [-1, 3, 0, -1],
              [-1, 0, 3, -1],
              [-1, -1, -1, 4]], dtype=float)

# Define a numpy array v of type float filled with your values. 
V = np.array([5, 0, 5, 0], dtype=float)

# Print the arrays A and v to check that they are correct.
print("A is \n", A, "\n \n and v is ", V)

A is 
 [[ 4. -1. -1. -1.]
 [-1.  3.  0. -1.]
 [-1.  0.  3. -1.]
 [-1. -1. -1.  4.]] 
 
 and v is  [5. 0. 5. 0.]


&#128309; Solve this system of equations using Gaussian elimination, following the code comments below. ✅

In [81]:
# Find nrows and ncols, the number of rows and columns in A.
nrows, ncols = A.shape
# Step through the rows of A. Make this loop readable!
for row in range(nrows): 
    # Divide the row entries in A and v by the diagonal element in A.
    V[row] /= A[row][row]
    A[row] /= A[row][row]
    # Step through the lower rows of A, and subtract multiples of the current row from the lower rows of A and v.
    for lower_row in range(row +1, nrows):
        V[lower_row] -= A[lower_row][row] * V[row]
        A[lower_row] -= A[lower_row][row] * A[row]
        
# ******** The following steps are for backsubstitution! *********
# Define a numpy array x of type float filled with zeros. Make it the same size as v. This will hold your solution.
X = np.zeros(V.shape, dtype=float)
# Step through the rows of A from the bottom up. 
for row in range(nrows-1, -1, -1):
    # Set the value of x at the current row to the value of v at the current row.
    X[row] = V[row]
    # For each lower row, subtract the appropriate multiple of x from the current row.
    for lower_row in range(row+1, nrows):
        X[row] -= A[row][lower_row] * X[lower_row]
# Print the solution x.
print(X)

[3.         1.66666667 3.33333333 2.        ]


&#128309; Print your final version of A to verify that it is upper triangular, and that all diagonal elements are 1. ✅

In [82]:
print(A)

[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.09090909 -0.45454545]
 [ 0.          0.          1.         -0.5       ]
 [ 0.          0.          0.          1.        ]]


&#128309; Let's do that in an easier way. Use  <a target="_blank" rel="noopener noreferrer"  href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html" >np.linalg.solve</a> to solve the above in a single line. Did you get the same answer? ✅

In [83]:
A = np.array([[4, -1, -1, -1],
              [-1, 3, 0, -1],
              [-1, 0, 3, -1],
              [-1, -1, -1, 4]], dtype=float)

V = np.array([5, 0, 5, 0], dtype=float)

X = np.linalg.solve(A, V)

print(X)

[3.         1.66666667 3.33333333 2.        ]


✍🏽 I did get the same answer! This makes sense as both methods should end up at the same answer.

&#128310; Translate your solution to sentences, i.e., write out in words what your solution to the resistor problem is. ✅

✍🏽 In words, the voltage at $V_1$ is 3V, the voltage at $V_2$ is 1.667V, the voltage at $V_3$ is 3.333V, and the voltage at $V_4$ is 2V. We used the system of linear equations to solve the Ohm's laws constraints to find the voltage at each point in our circuit.

&#128310; What if we started out with a matrix $\mathbf{A}$ that had a 0 as its upper lefthand value? What could we have done in our algorithm to avoid trouble? ✅

✍🏽 If this was the case, we could've added a different row over back to the upper row to ensure we didn't have a 0 lefthand corner value. We could also just have swapped two rows to ensure that this wasn't the case. Both of these methods would've ensured that matrix A didn't have 0 as an upper lefthand value.

# Acknolwedgments

S.E. Clark 2024, with resistor problem adapted from Newman 2013.